language: scala
branches:
  only:
    - master
    - /^v\d+(\.\d+)+$/
install:
  - pip3 install jep
script:
  - sbt test
after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./publish.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$TRAVIS_TAG" ]; then bash ./publish.sh; fi'
